### ISSUE TITLE
Error trying to start the app

### ISSUE THREAD

**Issue by dcts** [morochena/rails-in-electron#1]
Hey! Just followed the install instructions but could not get it to run. Getting the following error:

```
/home/dcts/code/rails-in-electron/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
```

**Comment by dcts** [comment]
running this fixed my issue (im on linux):

```
sudo apt-get install libgconf-2-4
```
Explenation here: https://github.com/balena-io/etcher/issues/2191#issuecomment-488355223



**But now I get the following error**:
```
Gtk-Message: 15:05:10.917: Failed to load module "canberra-gtk-module"
(electron:30255): Pango-ERROR **: 15:05:11.003: Harfbuzz version too old (1.0.6)
```

**Comment by morochena** [comment]
Hi, Rails and Electron were both wildly out of date so I've updated those. I hope that helps.
